swagger: "2.0"
info:
  title: Chirp API
  description: API for a social network with donations.
  version: 1.0.0

host: api.example.com
basePath: /v1
schemes:
  - https

paths:
  /messages:
    get:
      summary: 'Return recent messages.'
      produces:
        - application/json
      responses:
        200:
          description: 'List of messages. transactionId may be empty.'
          schema:
            title: messageList
            type: array
            items:
              $ref: '#/definitions/Message'
    post:
      summary: Add a new message.
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: message
          description: 'Message with optional donation.'
          schema:
            $ref: '#definitions/Message'
      responses:
        200:
          description: OK
        403:
          description: 'Improperly formatted post'
  /transactions:
    post:
      summary: Process a donation.
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: trasnaction
          description: 'Payment information from client. Transaction ID is empty.'
          schema:
            $ref: '#/definitions/Transaction'
      responses:
        200:
          description: 'Transaction ID is now populated.'
          schema:
            $ref: '#/definitions/Transaction'
        403:
          description: 'Improperly formatted post'
definitions:
  Message:
    type: 'object'
    required:
      - 'text'
    properties:
      text:
        type: string
      id:
        type: string
        format: uuid
      donation:
        type: object
        properties:
          amount:
            type: number
            format: float
          currency:
            $ref: '#definitions/Currency'
          orgCode:
            type: string
          orgName:
            type: string
          transactionId:
            type: string
            format: uuid
  Transaction:
    type: 'object'
    required:
      - cardNumber
      - amount
      - currency
    properties:
      cardNumber:
        type: string
        format: 'Credit card number'
      amount:
        type: number
        format: float
      orgCode:
        type: string
      currency:
        $ref: '#definitions/Currency'
      transactionId:
        type: string
        format: uuid
  Currency:
    type: string
    enum:
      - USD
      - GBP
      - EUR
